// Code generated by github.com/brezzgg/go-packages/confgen. DO NOT EDIT.
package config

// =============== Generate ===============

// App generated from hcl generate "app".
type App struct {
	// Env generated from hcl field "env". Default value is "production". 
	Env string `yaml:"env" json:"env"`
	// Debug generated from hcl field "debug". Default value is false. 
	Debug bool `yaml:"debug" json:"debug"`
	// Server generated from hcl field "server". Default value is DefaultServer(). 
	Server Server `yaml:"server" json:"server"`
	// Postgres generated from hcl field "postgres". Default value is DefaultPostgres(). 
	Postgres Postgres `yaml:"postgres" json:"postgres"`
	// Redis generated from hcl field "redis". Default value is DefaultRedis(). 
	Redis Redis `yaml:"redis" json:"redis"`
	// Kafka generated from hcl field "kafka". Default value is DefaultKafka(). 
	Kafka Kafka `yaml:"kafka" json:"kafka"`
	// Log generated from hcl field "log". Default value is DefaultLog(). 
	Log Log `yaml:"log" json:"log"`
}

// =============== Objects ===============

// Kafka generated from hcl object "kafka".
type Kafka struct {
	// Brokers generated from hcl field "brokers". Default value is nil. 
	Brokers []KafkaBroker `yaml:"brokers" json:"brokers"`
	// Topic generated from hcl field "topic". Default value is "events". 
	Topic string `yaml:"topic" json:"topic"`
	// GroupId generated from hcl field "group_id". Default value is "app-group". 
	GroupId string `yaml:"group_id" json:"group_id"`
	// MaxRetries generated from hcl field "max_retries". Default value is 3. 
	MaxRetries int `yaml:"max_retries" json:"max_retries"`
}

// KafkaBroker generated from hcl object "kafka_broker".
type KafkaBroker struct {
	// Address generated from hcl field "address". Default value is "localhost:9092". 
	// Description: remote host of kafka broker instance
	Address string `yaml:"address" json:"address"`
}

// Log generated from hcl object "log".
type Log struct {
	// Level generated from hcl field "level". Default value is "info". 
	Level string `yaml:"level" json:"level"`
	// Format generated from hcl field "format". Default value is "json". 
	Format string `yaml:"format" json:"format"`
	// Output generated from hcl field "output". Default value is "". Field is requred.
	Output string `yaml:"output" json:"output" confgen_required:"true"`
}

// Pool generated from hcl object "pool".
type Pool struct {
	// MaxOpen generated from hcl field "max_open". Default value is 10. 
	MaxOpen int `yaml:"max_open" json:"max_open"`
	// MaxIdle generated from hcl field "max_idle". Default value is 5. 
	MaxIdle int `yaml:"max_idle" json:"max_idle"`
	// MaxLifetime generated from hcl field "max_lifetime". Default value is 300. 
	MaxLifetime int64 `yaml:"max_lifetime" json:"max_lifetime"`
}

// Postgres generated from hcl object "postgres".
type Postgres struct {
	// Host generated from hcl field "host". Default value is "localhost". 
	Host string `yaml:"host" json:"host"`
	// Port generated from hcl field "port". Default value is 5432. 
	Port int `yaml:"port" json:"port"`
	// User generated from hcl field "user". Default value is "". Field is requred.
	User string `yaml:"user" json:"user" confgen_required:"true"`
	// Password generated from hcl field "password". Default value is "". Field is requred.
	Password string `yaml:"password" json:"password" confgen_required:"true"`
	// Dbname generated from hcl field "dbname". Default value is "app". 
	Dbname string `yaml:"dbname" json:"dbname"`
	// Pool generated from hcl field "pool". Default value is DefaultPool(). 
	Pool Pool `yaml:"pool" json:"pool"`
	// Tls generated from hcl field "tls". Default value is DefaultTls(). 
	Tls Tls `yaml:"tls" json:"tls"`
}

// Redis generated from hcl object "redis".
type Redis struct {
	// Host generated from hcl field "host". Default value is "localhost". 
	Host string `yaml:"host" json:"host"`
	// Port generated from hcl field "port". Default value is 6379. 
	Port int `yaml:"port" json:"port"`
	// Password generated from hcl field "password". Default value is "". 
	Password string `yaml:"password" json:"password"`
	// Db generated from hcl field "db". Default value is 0. 
	Db int `yaml:"db" json:"db"`
	// Pool generated from hcl field "pool". Default value is DefaultPool(). 
	Pool Pool `yaml:"pool" json:"pool"`
}

// Server generated from hcl object "server".
type Server struct {
	// Host generated from hcl field "host". Default value is "0.0.0.0". 
	// Description: listen host
	Host string `yaml:"host" json:"host"`
	// Admins generated from hcl field "admins". Default value is nil. 
	Admins []ServerAdmins `yaml:"admins" json:"admins"`
	// Port generated from hcl field "port". Default value is 8080. 
	Port int `yaml:"port" json:"port"`
	// ReadTimeout generated from hcl field "read_timeout". Default value is 30. 
	ReadTimeout int64 `yaml:"read_timeout" json:"read_timeout"`
	// WriteTimeout generated from hcl field "write_timeout". Default value is 30. 
	WriteTimeout int64 `yaml:"write_timeout" json:"write_timeout"`
	// Tls generated from hcl field "tls". Default value is DefaultTls(). 
	Tls Tls `yaml:"tls" json:"tls"`
}

// ServerAdmins generated from hcl object "server_admins".
type ServerAdmins struct {
	// Token generated from hcl field "token". Default value is "". Field is requred.
	// Description: base64 128 symbols
	Token string `yaml:"token" json:"token" confgen_required:"true"`
	// Name generated from hcl field "name". Default value is "". Field is requred.
	// Description: >= 3 symbols
	Name string `yaml:"name" json:"name" confgen_required:"true"`
}

// Tls generated from hcl object "tls".
type Tls struct {
	// CertFile generated from hcl field "cert_file". Default value is "". Field is requred.
	// Description: example cert.pem
	CertFile string `yaml:"cert_file" json:"cert_file" confgen_required:"true"`
	// KeyFile generated from hcl field "key_file". Default value is "". Field is requred.
	// Description: example key.pem
	KeyFile string `yaml:"key_file" json:"key_file" confgen_required:"true"`
}

// =============== Generate.Default ===============

// DefaultApp returns instance of hcl generate App with default values.
func DefaultApp() App {
	return App{
		Env: "production",
		Debug: false,
		Server: DefaultServer(),
		Postgres: DefaultPostgres(),
		Redis: DefaultRedis(),
		Kafka: DefaultKafka(),
		Log: DefaultLog(),
	}
}

// =============== Objects.Default ===============

// DefaultKafka returns instance of hcl object Kafka with default values.
func DefaultKafka() Kafka {
	return Kafka{
		Brokers: nil,
		Topic: "events",
		GroupId: "app-group",
		MaxRetries: 3,
	}
}

// DefaultKafkaBroker returns instance of hcl object KafkaBroker with default values.
func DefaultKafkaBroker() KafkaBroker {
	return KafkaBroker{
		Address: "localhost:9092",
	}
}

// DefaultLog returns instance of hcl object Log with default values.
func DefaultLog() Log {
	return Log{
		Level: "info",
		Format: "json",
		Output: "",
	}
}

// DefaultPool returns instance of hcl object Pool with default values.
func DefaultPool() Pool {
	return Pool{
		MaxOpen: 10,
		MaxIdle: 5,
		MaxLifetime: 300,
	}
}

// DefaultPostgres returns instance of hcl object Postgres with default values.
func DefaultPostgres() Postgres {
	return Postgres{
		Host: "localhost",
		Port: 5432,
		User: "",
		Password: "",
		Dbname: "app",
		Pool: DefaultPool(),
		Tls: DefaultTls(),
	}
}

// DefaultRedis returns instance of hcl object Redis with default values.
func DefaultRedis() Redis {
	return Redis{
		Host: "localhost",
		Port: 6379,
		Password: "",
		Db: 0,
		Pool: DefaultPool(),
	}
}

// DefaultServer returns instance of hcl object Server with default values.
func DefaultServer() Server {
	return Server{
		Host: "0.0.0.0",
		Admins: nil,
		Port: 8080,
		ReadTimeout: 30,
		WriteTimeout: 30,
		Tls: DefaultTls(),
	}
}

// DefaultServerAdmins returns instance of hcl object ServerAdmins with default values.
func DefaultServerAdmins() ServerAdmins {
	return ServerAdmins{
		Token: "",
		Name: "",
	}
}

// DefaultTls returns instance of hcl object Tls with default values.
func DefaultTls() Tls {
	return Tls{
		CertFile: "",
		KeyFile: "",
	}
}

// =============== Generate.Default func ===============

// Defaults returns result of DefaultApp.
func (c App) Defaults() any {
	return DefaultApp()
}

// =============== Objects.Default func ===============

// Defaults returns result of DefaultKafka.
func (c Kafka) Defaults() any {
	return DefaultKafka()
}

// Defaults returns result of DefaultKafkaBroker.
func (c KafkaBroker) Defaults() any {
	return DefaultKafkaBroker()
}

// Defaults returns result of DefaultLog.
func (c Log) Defaults() any {
	return DefaultLog()
}

// Defaults returns result of DefaultPool.
func (c Pool) Defaults() any {
	return DefaultPool()
}

// Defaults returns result of DefaultPostgres.
func (c Postgres) Defaults() any {
	return DefaultPostgres()
}

// Defaults returns result of DefaultRedis.
func (c Redis) Defaults() any {
	return DefaultRedis()
}

// Defaults returns result of DefaultServer.
func (c Server) Defaults() any {
	return DefaultServer()
}

// Defaults returns result of DefaultServerAdmins.
func (c ServerAdmins) Defaults() any {
	return DefaultServerAdmins()
}

// Defaults returns result of DefaultTls.
func (c Tls) Defaults() any {
	return DefaultTls()
}
