package template

const GoTemplate = `// Code generated by github.com/brezzgg/go-packages/confgen. DO NOT EDIT.
package {{.Output.Package}}

// =============== Generate ===============
{{range .Generate}}
// {{ToPascal .Name}} generated from hcl generate "{{.Name}}".
type {{ToPascal .Name}} struct {
{{- range .Fields}}
	// {{ToPascal .Name}} generated from hcl field "{{.Name}}". Default value is {{ToDefault .}}. {{if (ToBool .Required)}}Field is requred.{{end}}{{if .Desc}}
	// Description: {{.Desc}}{{end}}
	{{ToPascal .Name}} {{ToType .}} {{ToTag .Name $.Output.Formats (ToBool .Required)}}
{{- end}}
}
{{end}}
// =============== Objects ===============
{{range .Objects}}
// {{ToPascal .Name}} generated from hcl object "{{.Name}}".
type {{ToPascal .Name}} struct {
{{- range .Fields}}
	// {{ToPascal .Name}} generated from hcl field "{{.Name}}". Default value is {{ToDefault .}}. {{if (ToBool .Required)}}Field is requred.{{end}}{{if .Desc}}
	// Description: {{.Desc}}{{end}}
	{{ToPascal .Name}} {{ToType .}} {{ToTag .Name $.Output.Formats (ToBool .Required)}}
{{- end}}
}
{{end}}
// =============== Generate.Default ===============
{{range .Generate}}
// Default{{ToPascal .Name}} returns instance of hcl generate {{ToPascal .Name}} with default values.
func Default{{ToPascal .Name}}() {{ToPascal .Name}} {
	return {{ToPascal .Name}}{
{{- range .Fields}}
		{{ToPascal .Name}}: {{ToDefault .}},
{{- end}}
	}
}
{{end}}
// =============== Objects.Default ===============
{{range .Objects}}
// Default{{ToPascal .Name}} returns instance of hcl object {{ToPascal .Name}} with default values.
func Default{{ToPascal .Name}}() {{ToPascal .Name}} {
	return {{ToPascal .Name}}{
{{- range .Fields}}
		{{ToPascal .Name}}: {{ToDefault .}},
{{- end}}
	}
}
{{end}}
// =============== Generate.Default func ===============
{{range .Generate}}
// Defaults returns result of Default{{ToPascal .Name}}.
func (c {{ToPascal .Name}}) Defaults() any {
	return Default{{ToPascal .Name}}()
}
{{end}}
// =============== Objects.Default func ===============
{{range .Objects}}
// Defaults returns result of Default{{ToPascal .Name}}.
func (c {{ToPascal .Name}}) Defaults() any {
	return Default{{ToPascal .Name}}()
}
{{end}}`
